steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo -e "NOTION_CLIENT_ID=$$NOTION_CLIENT_ID\nNOTION_REDIRECT_URI=$$NOTION_REDIRECT_URI\nAUTH_SECRET=$$AUTH_SECRET\nDATABASE_URL=$$DATABASE_URL\nNOTION_CLIENT_SECRET=$$NOTION_CLIENT_SECRET" > .env
